version: '3.4'

services:
  web:
    image: ricky_web_image
    networks:
      - ricky_net
    ports:
      - "80:80"
    links:
      - was:ricky
    entrypoint:
      - "nginx"
      - "-g"
      - "daemon off;"
    depends_on:
      - was
  was:
    image: ricky_app_image
    networks:
      - ricky_net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - db:ricky_db
    entrypoint:
      - "java"
      - "-jar"
      - "-Duser.timezone=Asia/Seoul"
      - "/ricky.jar"
    depends_on:
      - db
  db:
    image: mysql
    networks:
      - ricky_net
    environment:
      - MYSQL_DATABASE=ricky_schema
      - MYSQL_USER=ricky
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /build/DB/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  ricky_net:

  

